### ISSUE TITLE
goroutine 1 [running]:

### ISSUE THREAD

**Issue by faithhopelove-jj** [jweissig/sense#1]
Hello, I was wondering if how to fix this error below.

I am running an Raspberry 4:
with go1.8.linux-armv6l.tar.gz and raspian armv71

i2c is also open:

pi@raspberrypi:~ $ sudo  i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

   **$ go run sense.go**
panic: open /dev/i2c-0: no such file or directory

goroutine 1 [running]:
main.main()
        /home/pi/trz-lib/sense/sense.go:33 +0x80
exit status 2

I got this error.

I hope you could help me. 

Thank you

**Comment by faithhopelove-jj** [comment]
**I have change :

    _//Device: "/dev/i2c-0",_

        // thermal sensor
        amg, err := amg8833.NewAMG8833(&amg8833.Opts{
                Device: "/dev/i2c-1",
                Mode:   amg8833.AMG88xxNormalMode,
                Reset:  amg8833.AMG88xxInitialReset,
                FPS:    amg8833.AMG88xxFPS1,
        })**
----------------------------------------------------------------------------------------------------

and I still got:

panic: write /dev/i2c-1: remote I/O error

goroutine 1 [running]:
github.com/jweissig/amg8833.(*AMG88xx).SetMode(0x2410648, 0x2410600)
        /home/pi/go/src/github.com/jweissig/amg8833/amg8833.go:133 +0xe0
github.com/jweissig/amg8833.NewAMG8833(0x243ff5c, 0x1, 0x0, 0xb23dc)
        /home/pi/go/src/github.com/jweissig/amg8833/amg8833.go:83 +0xb4
main.main()
        /home/pi/trz-lib/sense/sense.go:26 +0x4c

**Comment by faithhopelove-jj** [comment]
PS: I am using a usb mini to USB AMG8833
